<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);

        App\User::insert([
            'name' => "Admin",
            'last_name' => "RCL",
            'email' => "rcl@mail.com",
            'usuario' => "admin",
            'rol' => 1,
            'email_verified_at' => now(),
            'password' => Hash::make('jcuerorcl'), 
            'remember_token' => Str::random(10),
        ]);

        App\User::insert([
            'name' => "Jairo",
            'last_name' => "Cuero",
            'email' => "jadacuor16@gmail.com",
            'usuario' => "jairocuero",
            'rol' => 2,
            'email_verified_at' => now(),
            'password' => Hash::make('jcuerorcl'), 
            'remember_token' => Str::random(10),
        ]);

        App\User::insert([
            'name' => "Camilo",
            'last_name' => "Torres",
            'email' => "estudiante@mail.com",
            'usuario' => "camilo.torres",
            'rol' => 3,
            'creado' => 2,
            'email_verified_at' => now(),
            'password' => Hash::make('ctorres2020'), 
            'remember_token' => Str::random(10),
        ]);

        App\User::insert([ 'name' => "brayan", 
'last_name' => "calderon", 
'email' => "brayan.calderon.salamanca@unillanos.edu.co", 
'usuario' => "brayan.calderon", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('bra67ron'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "daiam", 
'last_name' => "parrado", 
'email' => "daiam.parrado@unillanos.edu.co", 
'usuario' => "daiam.parrado", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('dai56ado'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "diana", 
'last_name' => "monroy", 
'email' => "diana.monroy@unillanos.edu.co", 
'usuario' => "diana.monroy", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('dia55roy'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "didier", 
'last_name' => "alvarez", 
'email' => "didier.alvarez@unillanos.edu.co", 
'usuario' => "didier.alvarez", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('did66rez'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "edgar", 
'last_name' => "alferez", 
'email' => "edgar.alferez@unillanos.edu.co", 
'usuario' => "edgar.alferez", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('edg56rez'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "hugo", 
'last_name' => "ruiz", 
'email' => "hugo.ruiz@unillanos.edu.co", 
'usuario' => "hugo.ruiz", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('hug43uiz'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "john", 
'last_name' => "sanchez", 
'email' => "john.sanchez.fierro@unillanos.edu.co", 
'usuario' => "john.sanchez", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('joh46hez'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "jose", 
'last_name' => "camacho", 
'email' => "jose.camacho@unillanos.edu.co", 
'usuario' => "jose.camacho", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('jos46cho'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "julian", 
'last_name' => "bastos", 
'email' => "julian.bastos@unillanos.edu.co", 
'usuario' => "julian.bastos", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('jul65tos'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "kevin", 
'last_name' => "gonzalez", 
'email' => "kevin.gonzalez@unillanos.edu.co", 
'usuario' => "kevin.gonzalez", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('kev57lez'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "luis", 
'last_name' => "rodriguez", 
'email' => "luis.rodriguez.nunez@unillanos.edu.co", 
'usuario' => "luis.rodriguez", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('lui48uez'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "marylin", 
'last_name' => "martinez", 
'email' => "marylin.martinez@unillanos.edu.co", 
'usuario' => "marylin.martinez", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('mar77nez'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "oscar", 
'last_name' => "vargas", 
'email' => "oscar.vargas.mora@unillanos.edu.co", 
'usuario' => "oscar.vargas", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('osc55gas'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "pedro", 
'last_name' => "perez", 
'email' => "pedro.perez@unillanos.edu.co", 
'usuario' => "pedro.perez", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('ped54rez'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "raul", 
'last_name' => "mora", 
'email' => "raul.mora@unillanos.edu.co", 
'usuario' => "raul.mora", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('rau43ora'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "sandro", 
'last_name' => "martinez", 
'email' => "sandro.martinez@unillanos.edu.co", 
'usuario' => "sandro.martinez", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('san67nez'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "santos", 
'last_name' => "cordero", 
'email' => "santos.cordero@unillanos.edu.co", 
'usuario' => "santos.cordero", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('san66ero'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "diana", 
'last_name' => "diaz", 
'email' => "diana.diaz.rincon@unillanos.edu.co", 
'usuario' => "diana.diaz", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('dia53iaz'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "yull", 
'last_name' => "villalobos", 
'email' => "yull.villalobos@unillanos.edu.co", 
'usuario' => "yull.villalobos", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('yul49bos'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "juan", 
'last_name' => "vera", 
'email' => "juan.vera@unillanos.edu.co", 
'usuario' => "juan.vera", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('jua43era'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "juan", 
'last_name' => "correa", 
'email' => "juan.correa@unillanos.edu.co", 
'usuario' => "juan.correa", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('jua45rea'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "jorge", 
'last_name' => "vargas", 
'email' => "jorge.vargas.munoz@unillanos.edu.co", 
'usuario' => "jorge.vargas", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('jor55gas'), 
'remember_token' => Str::random(10), 
  ]);
App\User::insert([ 'name' => "jennifer", 
'last_name' => "ochoa", 
'email' => "jennifer.ochoa@unillanos.edu.co", 
'usuario' => "jennifer.ochoa", 
'rol' => 3, 
'creado' => 2, 
'email_verified_at' => now(), 
'password' => Hash::make('jen84hoa'), 
'remember_token' => Str::random(10), 
  ]);


        App\Parameter::insert([
            'key' => "CAMERA1"
        ]);
    }
}
